### ISSUE TITLE
Startup Issue?

### ISSUE THREAD

**Issue by rjpear** [edurange/edurange-flask#4]
Hello..    I am having an issue getting things up and running in Docker.  I use the "docker-compose up flask-prod" command and the resulting script output ends in error.  Here is the fail point onward:  
lask-prod_1  |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
flask-prod_1  | sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not connect to server: Connection refused
flask-prod_1  | 	Is the server running on host "127.0.0.1" and accepting
flask-prod_1  | 	TCP/IP connections on port 5432?
flask-prod_1  | 
flask-prod_1  | (Background on this error at: http://sqlalche.me/e/e3q8)
flask-prod_1  | npm ERR! code ELIFECYCLE
flask-prod_1  | npm ERR! errno 1
flask-prod_1  | npm ERR! edurange_refactored@1.0.0 flask-static-digest: `flask digest compile`
flask-prod_1  | npm ERR! Exit status 1
flask-prod_1  | npm ERR! 
flask-prod_1  | npm ERR! Failed at the edurange_refactored@1.0.0 flask-static-digest script.
flask-prod_1  | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
flask-prod_1  | 
flask-prod_1  | npm ERR! A complete log of this run can be found in:
flask-prod_1  | npm ERR!     /home/sid/.npm/_logs/2020-10-09T12_48_13_884Z-debug.log
flask-prod_1  | npm ERR! code ELIFECYCLE
flask-prod_1  | npm ERR! errno 1
flask-prod_1  | npm ERR! edurange_refactored@1.0.0 build: `NODE_ENV=production webpack --progress --colors -p && npm run flask-static-digest`
flask-prod_1  | npm ERR! Exit status 1
flask-prod_1  | npm ERR! 
flask-prod_1  | npm ERR! Failed at the edurange_refactored@1.0.0 build script.
flask-prod_1  | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
flask-prod_1  | 
flask-prod_1  | npm ERR! A complete log of this run can be found in:
flask-prod_1  | npm ERR!     /home/sid/.npm/_logs/2020-10-09T12_48_13_974Z-debug.log

Any thoughts as to what I am missing?  Running on Ubuntu Server..     Thanks for any info... 
Rob

**Comment by coojac09** [comment]
Hello!
Sorry about the confusion, the docker deployment option is no longer supported for the moment and the Readme had not been updated to reflect that. 
I've just updated the Readme with the latest instructions and added a new installation script. 
For a more detailed breakdown of what that script does, or to do it manually, you can check our docs at 
https://github.com/edurange/edurange-flask-docs/blob/master/installation.md
Thank you for your interest in the project!
Jack

**Comment by rjpear** [comment]
Thanks for the update!
