### ISSUE TITLE
Jinga requirements preventing installation

### ISSUE THREAD

**Issue by sethlei** [edurange/edurange-flask#43]
I was installing Edurange today on a VM, and ran into this issue: 

```
> edurange_refactored@1.0.0 flask-static-digest
> flask digest compile

Traceback (most recent call last):
  File "/home/seth/.local/bin/flask", line 5, in <module>
    from flask.cli import main
  File "/home/seth/.local/lib/python3.8/site-packages/flask/__init__.py", line 14, in <module>
    from jinja2 import escape
ImportError: cannot import name 'escape' from 'jinja2' (/home/seth/.local/lib/python3.8/site-packages/jinja2/__init__.py)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! edurange_refactored@1.0.0 build: `NODE_ENV=production webpack --progress --colors -p && npm run flask-static-digest`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the edurange_refactored@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/seth/.npm/_logs/2022-04-07T20_47_18_435Z-debug.log
```

Stackoverflow on this issue: https://stackoverflow.com/a/71721006
Jinja documentation: https://jinja.palletsprojects.com/en/3.1.x/changes/#version-3-1-0

I tried adding jinja2<3.1.0 to /requirements/prod.txt, but that didn't seem to resolve the issue. My requirements.txt in the root folder points to prod.txt.

**Comment by cookjackc** [comment]
Todos:

prompt for all .env changes

awk/sed edit the .env instead of asking user to type same info

	Fields:
		Database URL
		Host_Extern
		Subnet_Octet
		Secret Key: Auto-Randomize?
		Flask_Username
		Password
		Root_password


new terraform version
check npm/pip module versions

install as non-root


Flask = 2.0.3
Werkzeug 2.0
click 7.1.2

Flask-WTF = 1.0.0
WTForms = 3.1.1
WTForms 3.0.1

email-validator 1.1.3

Debug Toolbar 0.13.1
